# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

def install_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shiritori_world
   pod 'Firebase/Auth', '6.14.0'
   pod 'Firebase/Firestore', '6.14.0'
   pod 'Firebase/Functions', '6.14.0'
   pod 'Firebase/Messaging', '6.14.0'
   pod 'Firebase/Storage', '6.14.0'
   pod 'Firebase/Analytics', '6.14.0'
   pod 'FBSDKLoginKit', '5.13.1'
   pod 'KeyboardObserving', '0.3.0'	
end

target 'shiritori_world_test' do
  install_pods
end

target 'shiritori_world_product' do
  install_pods
end
