# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'shiritori_world' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shiritori_world
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics', '6.14.0'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
    pod 'Firebase/Auth', '6.14.0'
    pod 'Firebase/Firestore', '6.14.0'
    pod 'Firebase/Functions', '6.14.0'
    pod 'Firebase/Messaging', '6.14.0'
    pod 'Firebase/Storage', '6.14.0'

    pod 'FBSDKLoginKit', '5.13.1'
end
